columns:
  name: object
  online_order: category
  book_table: category
  votes: int64
  location: object
  rest_type: object
  dish_liked: int64                     
  cuisines: int64                        
  approx_cost(for two people): float64                                           
  listed_in(type): object               
  listed_in(city): object
  Rate: float64
      

numerical_columns:
  - votes
  - dish_liked
  - cuisines
  - approx_cost(for two people)


categorical_columns:
  - online_order
  - book_table

target_column: Rate
